"""Shared helpers of the check scripts: the golden dump and the engine tools.

The golden dump (models/golden/cpu, regenerated by tools/native) is an
index.jsonl of {name, file, type, ne} entries next to the raw tensors.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import numpy as np


def load_index(dump: Path) -> dict[str, dict]:
    """name -> entry of the dump's index.jsonl."""
    idx: dict[str, dict] = {}
    for line in (dump / "index.jsonl").read_text().splitlines():
        entry = json.loads(line)
        idx[entry["name"]] = entry
    return idx


def load(dump: Path, entry: dict) -> np.ndarray:
    """One dumped tensor as f32, shaped as ggml's ne reversed (row-major)."""
    dtype = {"f32": np.float32, "f16": np.float16}[entry["type"]]
    flat = np.fromfile(dump / entry["file"], dtype=dtype).astype(np.float32)
    return flat.reshape(tuple(reversed(entry["ne"])))


def rel_diff(mine: np.ndarray, ref: np.ndarray) -> float:
    """max |mine - ref| relative to max |ref|."""
    scale = max(float(np.abs(ref).max()), 1e-12)
    return float(np.abs(mine - ref).max()) / scale


def run_tool(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    """Runs an engine tool, capturing its output; on failure prints what it said
    (the engine reports the cause on stderr) and exits with its status."""
    try:
        return subprocess.run(cmd, check=True, capture_output=True, **kwargs)
    except subprocess.CalledProcessError as exc:
        def text(b):
            return b if isinstance(b, str) else (b or b"").decode(errors="replace")
        print(f"command failed (exit {exc.returncode}): {' '.join(map(str, cmd))}", file=sys.stderr)
        for stream in (text(exc.stdout), text(exc.stderr)):
            if stream.strip():
                print(stream.rstrip(), file=sys.stderr)
        raise SystemExit(exc.returncode or 1) from None
