"""Generate engine/src/text/unicode_tables.hh: the code point classes of the tokenizer's
pre-tokenizer regex (#148), as sorted ranges with flags.

usage: uv run python gen_unicode_tables.py > ../engine/src/text/unicode_tables.hh

Classes: L (letters, general category L*), M (marks, M*), N (numbers, N*), and WS: the regex's
\\s. llama.cpp collapses every non-ASCII code point to a placeholder of its class and runs
std::regex, so \\s is C isspace() on ASCII (\\t \\n \\v \\f \\r and space) plus the non-ASCII
code points with the Unicode White_Space property.
"""

import sys
import unicodedata

# Unicode White_Space, non-ASCII part (PropList.txt; stable since Unicode 6.3)
WHITE_SPACE_NON_ASCII = [0x85, 0xA0, 0x1680] + list(range(0x2000, 0x200B)) + [0x2028, 0x2029,
                                                                              0x202F, 0x205F, 0x3000]
ASCII_SPACE = [0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20]

L, M, N, WS = 1, 2, 4, 8


def flags(cp: int) -> int:
    f = 0
    cat = unicodedata.category(chr(cp))
    if cat.startswith("L"):
        f |= L
    elif cat.startswith("M"):
        f |= M
    elif cat.startswith("N"):
        f |= N
    if cp in ASCII_SPACE or cp in WHITE_SPACE_NON_ASCII:
        f |= WS
    return f


def main() -> None:
    ranges = []
    start, cur = 0, flags(0)
    for cp in range(1, 0x110000):
        f = flags(cp)
        if f != cur:
            if cur:
                ranges.append((start, cp - 1, cur))
            start, cur = cp, f
    if cur:
        ranges.append((start, 0x10FFFF, cur))
    out = sys.stdout
    out.write(f"// Generated by tools/gen_unicode_tables.py (Unicode {unicodedata.unidata_version}, "
              "Python unicodedata): do not edit.\n")
    out.write("// Code point classes of the pre-tokenizer regex (#148): sorted, disjoint ranges.\n")
    out.write("#pragma once\n\n#include <cstdint>\n\nnamespace omph::text {\n\n")
    out.write("enum : uint8_t { kCpLetter = 1, kCpMark = 2, kCpNumber = 4, kCpSpace = 8 };\n\n")
    out.write("struct CpRange {\n    uint32_t first;\n    uint32_t last;\n    uint8_t flags;\n};\n\n")
    out.write(f"inline constexpr CpRange kCpRanges[{len(ranges)}] = {{\n")
    for a, b, f in ranges:
        out.write(f"    {{0x{a:X}, 0x{b:X}, {f}}},\n")
    out.write("};\n\n} // namespace omph::text\n")


if __name__ == "__main__":
    main()
