#!/usr/bin/env python3
"""Architecture sanity pass for the omphalos reference implementation (PLAN.md §9).

Reads GGUF metadata and the tensor table — tensor *data* is never loaded — and
writes a markdown fact sheet used by the reference forward pass and by the
engine's loader.

usage: uv run python inspect_gguf.py <model.gguf> [-o <out.md>]
"""

from __future__ import annotations

import argparse
import re
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
from gguf import GGUFReader


def _field_value(field):
    try:
        value = field.contents()
    except Exception:  # noqa: BLE001 -- any field gguf-py cannot decode is just skipped
        return None
    if isinstance(value, np.ndarray):
        if value.dtype.kind in "OSU":
            out = []
            for item in value.tolist():
                if isinstance(item, bytes):
                    item = item.decode("utf-8", "replace")
                out.append(item)
            return out
        return value.tolist()
    return value


def scalar(fields, key, default=None):
    value = _field_value(fields[key]) if key in fields else None
    if value is None:
        return default
    if isinstance(value, list) and len(value) == 1:
        return value[0]
    return value


def text(fields, key, default=""):
    value = scalar(fields, key)
    if value is None:
        return default
    if isinstance(value, bytes):
        return value.decode("utf-8", "replace")
    if isinstance(value, list):
        return " ".join(str(v) for v in value)
    return str(value)


def fmt_shape(shape):
    return "x".join(str(int(v)) for v in shape)


def main() -> None:
    ap = argparse.ArgumentParser(description="GGUF architecture fact sheet")
    ap.add_argument("model")
    ap.add_argument("-o", "--out", default=None)
    args = ap.parse_args()

    model = Path(args.model)
    reader = GGUFReader(model)
    fields = reader.fields
    arch = text(fields, "general.architecture", "unknown")

    type_hist = Counter()
    kind_count = defaultdict(int)
    kind_bytes = defaultdict(int)
    kind_types = defaultdict(Counter)
    layer_kinds = defaultdict(set)
    mtp_tensors = {}
    nonlayer = []
    total_bytes = 0

    for t in reader.tensors:
        name = t.name
        qtype = getattr(t.tensor_type, "name", str(t.tensor_type))
        nbytes = int(t.n_bytes)
        total_bytes += nbytes
        type_hist[qtype] += 1

        m = re.match(r"blk\.(\d+)\.(.+)", name)
        if m:
            layer, rest = int(m.group(1)), m.group(2)
            head = rest.split(".", 1)[0]
            layer_kinds[layer].add(head)
            if head == "nextn":
                mtp_tensors[name] = (qtype, fmt_shape(t.shape))
            kind = f"blk.*.{head}"
        else:
            kind = name.split(".", 1)[0]
            nonlayer.append((name, qtype, fmt_shape(t.shape), nbytes))

        kind_count[kind] += 1
        kind_bytes[kind] += nbytes
        kind_types[kind][qtype] += 1

    n_layers = int(scalar(fields, f"{arch}.block_count", 0))
    attn = sorted(l for l, ks in layer_kinds.items() if "attn_v" in ks)
    delta = sorted(l for l, ks in layer_kinds.items() if "ssm_a" in ks)
    mtp = sorted(l for l, ks in layer_kinds.items() if "nextn" in ks)

    lines = []
    add = lines.append
    add(f"# Model facts — `{model.name}`")
    add("")
    add("Generated by `tools/inspect_gguf.py` (PLAN.md §9); tensor data is never loaded.")
    add("")
    add("## Metadata")
    add("")
    add("| key | value |")
    add("|---|---|")
    interesting = [
        "general.architecture", "general.name", "general.size_label", "general.file_type",
        "general.quantization_version",
        f"{arch}.block_count", f"{arch}.context_length", f"{arch}.embedding_length",
        f"{arch}.feed_forward_length", f"{arch}.attention.head_count",
        f"{arch}.attention.head_count_kv", f"{arch}.attention.key_length",
        f"{arch}.attention.value_length", f"{arch}.attention.layer_norm_rms_epsilon",
        f"{arch}.rope.freq_base", f"{arch}.rope.dimension_count",
        f"{arch}.rope.dimension_sections",
        f"{arch}.ssm.conv_kernel", f"{arch}.ssm.state_size", f"{arch}.ssm.group_count",
        f"{arch}.ssm.time_step_rank", f"{arch}.ssm.inner_size",
        f"{arch}.full_attention_interval", f"{arch}.nextn_predict_layers",
        "tokenizer.ggml.model", "tokenizer.ggml.pre",
        "tokenizer.ggml.bos_token_id", "tokenizer.ggml.eos_token_id",
        "tokenizer.ggml.padding_token_id", "tokenizer.ggml.add_bos_token",
    ]
    for key in interesting:
        if key in fields:
            value = text(fields, key)
            if len(value) > 120:
                value = f"<{len(value)} chars>"
            add(f"| `{key}` | {value} |")
    add("")
    add("## Layer pattern")
    add("")
    add(f"- `{arch}.block_count` = {n_layers} blocks")
    add(f"- full-attention layers ({len(attn)}): {attn}")
    add(f"- Gated DeltaNet layers ({len(delta)}): {delta}")
    add(f"- MTP layer(s): {mtp}")
    add("")
    add("## Layer composition")
    add("")
    for label, layer in (
        ("DeltaNet", delta[0] if delta else None),
        ("full attention", attn[0] if attn else None),
        ("MTP", mtp[0] if mtp else None),
    ):
        if layer is not None:
            kinds = ", ".join(f"`{k}`" for k in sorted(layer_kinds[layer]))
            add(f"- {label} (blk.{layer}): {kinds}")
    add("")
    add("## Tensor inventory")
    add("")
    add(f"Total: {len(reader.tensors)} tensors, {total_bytes / 2**30:.2f} GiB")
    add("")
    add("| kind | count | bytes | types |")
    add("|---|---:|---:|---|")
    for kind in sorted(kind_count, key=lambda k: -kind_bytes[k]):
        types = ", ".join(f"{t}:{c}" for t, c in kind_types[kind].most_common())
        add(f"| `{kind}` | {kind_count[kind]} | {kind_bytes[kind] / 2**20:.1f} MiB | {types} |")
    add("")
    add("## Quant-type histogram")
    add("")
    for qtype, count in type_hist.most_common():
        add(f"- {qtype}: {count}")
    add("")
    if mtp_tensors:
        add("## MTP head tensors")
        add("")
        add("| tensor | type | shape |")
        add("|---|---|---|")
        for name, (qtype, shape) in sorted(mtp_tensors.items()):
            add(f"| `{name}` | {qtype} | {shape} |")
        add("")
    add("## Non-layer tensors")
    add("")
    add("| tensor | type | shape | bytes |")
    add("|---|---|---|---:|")
    for name, qtype, shape, nbytes in nonlayer:
        add(f"| `{name}` | {qtype} | {shape} | {nbytes} |")
    add("")

    out = Path(args.out) if args.out else Path(__file__).resolve().parent / "model-facts" / f"{model.stem}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    print(f"layers={n_layers} attn={len(attn)} delta={len(delta)} mtp={mtp} tensors={len(reader.tensors)}")


if __name__ == "__main__":
    main()
